services:
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=kestra
      - POSTGRES_PASSWORD=k3str4
      - POSTGRES_DB=weather_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


  pgadmin:
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=root
      ports:
        - "8085:80"
      volumes:
        - pgadmin-data:/var/lib/pgadmin
      depends_on:
        postgres:
          condition: service_started
          

volumes:
  postgres-data:
    name: postgres-data
  pgadmin-data:
    name: pgadmin-data
